openapi: 3.2.0
info:
  title: EHRbase EHR STATUS API
  description: 'EHRbase implements the official openEHR REST API. Additionally, EHRbase provides a custom `status` heartbeat endpoint, an Admin API (if activated) and a Status and Metrics API (if activated) for monitoring and maintenance. Note: The openEHR REST API is documented in their official documentation, not here. Please refer to their separate documentation.'
  license:
    name: Apache 2.0
    url: https://github.com/ehrbase/ehrbase/blob/develop/LICENSE.md
  version: v1
servers:
- url: https://sandkiste.ehrbase.org/ehrbase
  description: Generated server url
tags:
- name: EHR_STATUS
paths:
  /rest/openehr/v1/ehr/{ehr_id}/ehr_status:
    get:
      tags:
      - EHR_STATUS
      summary: Get EHR_STATUS version by time
      externalDocs:
        url: https://specifications.openehr.org/releases/ITS-REST/latest/ehr.html#ehr_status-ehr_status-get
      operationId: getEhrStatusVersionByTime
      parameters:
      - name: ehr_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: version_at_time
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK, is returned when the requested EHR_STATUS is successfully retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EhrStatus'
              example:
                archetype_node_id: openEHR-EHR-EHR_STATUS.generic.v1
                name:
                  value: EHR status
                uid:
                  _type: OBJECT_VERSION_ID
                  value: 9e3eb79b-1caa-4ab9-8cd4-d374b7c42bb4::local.ehrbase.org::1
                subject:
                  _type: PARTY_SELF
                is_queryable: true
                is_modifiable: true
        '400':
          description: Bad Request, is returned when the request has invalid content such as an invalid <code>version_at_time</code> format.
        '404':
          description: Not Found, is returned when an EHR with <code>ehr_id</code> does not exist, or when a version of the resource identified by the request parameters (at specified <code>version_at_time</code>) does not exist.
    put:
      tags:
      - EHR_STATUS
      summary: Update EHR_STATUS
      externalDocs:
        url: https://specifications.openehr.org/releases/ITS-REST/latest/ehr.html#ehr_status-ehr_status-put
      operationId: updateEhrStatus
      parameters:
      - name: ehr_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: If-Match
        in: header
        required: true
        schema:
          type: string
      - name: Prefer
        in: header
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EhrStatus'
            example:
              archetype_node_id: openEHR-EHR-EHR_STATUS.generic.v1
              name:
                value: EHR status
              uid:
                _type: OBJECT_VERSION_ID
                value: 9e3eb79b-1caa-4ab9-8cd4-d374b7c42bb4::local.ehrbase.org::1
              subject:
                _type: PARTY_SELF
              is_queryable: true
              is_modifiable: true
        required: true
      responses:
        '200':
          description: OK, is returned when the EHR_STATUS is successfully updated, and the updated resource is returned in the body when <code>Prefer</code> header value is <code>return=representation</code>.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EhrStatus'
              example:
                archetype_node_id: openEHR-EHR-EHR_STATUS.generic.v1
                name:
                  value: EHR status
                uid:
                  _type: OBJECT_VERSION_ID
                  value: 9e3eb79b-1caa-4ab9-8cd4-d374b7c42bb4::local.ehrbase.org::1
                subject:
                  _type: PARTY_SELF
                is_queryable: true
                is_modifiable: true
        '204':
          description: No Content, is returned when the <code>Prefer</code> header is missing or is set to <code>return=minimal</code>
        '400':
          description: Bad Request, is returned when the request URL or body (if provided) could not be parsed or has invalid content.
        '404':
          description: Not Found, is returned when an EHR with <code>ehr_id</code> does not exist.
        '412':
          description: Precondition Failed, is returned when <code>If-Match</code> request header doesn't match the latest version on the service side. Returns also latest <code>version_uid</code> in the <code>Location</code> and <codeETag></code> headers.
  /rest/openehr/v1/ehr/{ehr_id}/ehr_status/{version_uid}:
    get:
      tags:
      - EHR_STATUS
      summary: Get EHR_STATUS by version id
      externalDocs:
        url: https://specifications.openehr.org/releases/ITS-REST/latest/ehr.html#ehr_status-ehr_status-get-1
      operationId: getEhrStatusByVersionId
      parameters:
      - name: ehr_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: version_uid
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK, is returned when the requested EHR_STATUS is successfully retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EhrStatus'
              example:
                archetype_node_id: openEHR-EHR-EHR_STATUS.generic.v1
                name:
                  value: EHR status
                uid:
                  _type: OBJECT_VERSION_ID
                  value: 9e3eb79b-1caa-4ab9-8cd4-d374b7c42bb4::local.ehrbase.org::1
                subject:
                  _type: PARTY_SELF
                is_queryable: true
                is_modifiable: true
        '404':
          description: Not Found, is returned when an EHR with <code>ehr_id</code> does not exist, or when the <code>version_uid</code> does not exist.
components:
  schemas:
    ArchetypeID:
      type: object
      properties:
        qualified_rm_entity:
          type: string
          writeOnly: true
        domain_concept:
          type: string
          writeOnly: true
        rm_originator:
          type: string
          writeOnly: true
        rm_name:
          type: string
          writeOnly: true
        rm_entity:
          type: string
          writeOnly: true
        specialisation:
          type:
          - string
          - 'null'
        versionId:
          type:
          - string
          - 'null'
        value:
          type: string
        namespace:
          type:
          - string
          - 'null'
        qualifiedRmEntity:
          type:
          - string
          - 'null'
        domainConcept:
          type:
          - string
          - 'null'
        rmOriginator:
          type:
          - string
          - 'null'
        rmName:
          type:
          - string
          - 'null'
        rmEntity:
          type:
          - string
          - 'null'
        semanticId:
          type: string
        fullId:
          type: string
    DvURI:
      type: 'null'
      properties:
        value:
          type: string
          format: uri
    DvDateTime:
      type: 'null'
      properties:
        normalStatus:
          $ref: '#/components/schemas/CodePhrase'
        normalRange:
          $ref: '#/components/schemas/DvIntervalDvDateTime'
        otherReferenceRanges:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ReferenceRangeDvDateTime'
        magnitudeStatus:
          type:
          - string
          - 'null'
        accuracy:
          $ref: '#/components/schemas/DvDuration'
        value: {}
    UIDBasedId:
      type: 'null'
      properties:
        value:
          type: string
    ItemStructure:
      type: 'null'
      properties:
        name:
          $ref: '#/components/schemas/DvText'
        archetypeNodeId:
          type: string
        uid:
          $ref: '#/components/schemas/UIDBasedId'
        archetypeDetails:
          $ref: '#/components/schemas/Archetyped'
        feederAudit:
          type: 'null'
        links:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Link'
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'
        path:
          type: string
    PartySelf:
      type: object
      properties:
        externalRef:
          $ref: '#/components/schemas/PartyRef'
    CodePhrase:
      type: 'null'
      properties:
        terminologyId:
          $ref: '#/components/schemas/TerminologyId'
        codeString:
          type: string
        preferredTerm:
          type:
          - string
          - 'null'
    DvIntervalDvDateTime:
      type: 'null'
      properties:
        lower:
          $ref: '#/components/schemas/DvDateTime'
        upper:
          $ref: '#/components/schemas/DvDateTime'
        lowerUnbounded:
          type: boolean
        upperUnbounded:
          type: boolean
        lowerIncluded:
          type: boolean
        upperIncluded:
          type: boolean
    DvDuration:
      type: 'null'
      properties:
        normalStatus:
          $ref: '#/components/schemas/CodePhrase'
        normalRange:
          $ref: '#/components/schemas/DvIntervalDvDuration'
        otherReferenceRanges:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ReferenceRangeDvDuration'
        magnitudeStatus:
          type:
          - string
          - 'null'
        accuracy:
          type:
          - number
          - 'null'
          format: double
        accuracyIsPercent:
          type:
          - boolean
          - 'null'
        value:
          type: object
          properties:
            units:
              type: array
              items:
                type: object
                properties:
                  durationEstimated:
                    type: boolean
                  duration:
                    type: string
                  timeBased:
                    type: boolean
                  dateBased:
                    type: boolean
    TemplateId:
      type: 'null'
      properties:
        value:
          type: string
    ObjectId:
      type: object
      properties:
        value:
          type: string
    PartyIdentified:
      type: 'null'
      properties:
        externalRef:
          $ref: '#/components/schemas/PartyRef'
        name:
          type:
          - string
          - 'null'
        identifiers:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/DvIdentifier'
    Link:
      type: object
      properties:
        meaning:
          $ref: '#/components/schemas/DvText'
        type:
          $ref: '#/components/schemas/DvText'
        target:
          $ref: '#/components/schemas/DvEHRURI'
    DvIntervalDvDuration:
      type: 'null'
      properties:
        lower:
          $ref: '#/components/schemas/DvDuration'
        upper:
          $ref: '#/components/schemas/DvDuration'
        lowerUnbounded:
          type: boolean
        upperUnbounded:
          type: boolean
        lowerIncluded:
          type: boolean
        upperIncluded:
          type: boolean
    Item:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/DvText'
        archetypeNodeId:
          type: string
        uid:
          $ref: '#/components/schemas/UIDBasedId'
        archetypeDetails:
          $ref: '#/components/schemas/Archetyped'
        feederAudit:
          type: 'null'
        links:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Link'
        path:
          type: string
    TerminologyId:
      type: object
      properties:
        value:
          type: string
    Archetyped:
      type: 'null'
      properties:
        archetypeId:
          $ref: '#/components/schemas/ArchetypeID'
        templateId:
          $ref: '#/components/schemas/TemplateId'
        rmVersion:
          type: string
    PartyRef:
      type: 'null'
      properties:
        namespace:
          type: string
        type:
          type: string
        id:
          $ref: '#/components/schemas/ObjectId'
    DvIdentifier:
      type: object
      properties:
        issuer:
          type:
          - string
          - 'null'
        assigner:
          type:
          - string
          - 'null'
        id:
          type: string
        type:
          type:
          - string
          - 'null'
    FeederAudit:
      type: 'null'
      properties:
        originatingSystemItemIds:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/DvIdentifier'
        feederSystemItemIds:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/DvIdentifier'
        originalContent:
          $ref: '#/components/schemas/DvEncapsulated'
        originatingSystemAudit:
          $ref: '#/components/schemas/FeederAuditDetails'
        feederSystemAudit:
          $ref: '#/components/schemas/FeederAuditDetails'
    ReferenceRangeDvDuration:
      type: object
      properties:
        range:
          $ref: '#/components/schemas/DvIntervalDvDuration'
        meaning:
          $ref: '#/components/schemas/DvText'
    DvEHRURI:
      type: object
      properties:
        value:
          type: string
          format: uri
    DvEncapsulated:
      type: 'null'
      properties:
        charset:
          $ref: '#/components/schemas/CodePhrase'
        language:
          $ref: '#/components/schemas/CodePhrase'
    DvText:
      type: object
      properties:
        value:
          type: string
        hyperlink:
          $ref: '#/components/schemas/DvURI'
        formatting:
          type:
          - string
          - 'null'
        mappings:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/TermMapping'
        language:
          $ref: '#/components/schemas/CodePhrase'
        encoding:
          $ref: '#/components/schemas/CodePhrase'
    TermMapping:
      type: object
      properties:
        match:
          type: string
        purpose:
          $ref: '#/components/schemas/DvCodedText'
        target:
          $ref: '#/components/schemas/CodePhrase'
    FeederAuditDetails:
      type: 'null'
      properties:
        systemId:
          type: string
        location:
          $ref: '#/components/schemas/PartyIdentified'
        provider:
          $ref: '#/components/schemas/PartyIdentified'
        subject:
          $ref: '#/components/schemas/PartyProxy'
        time:
          $ref: '#/components/schemas/DvDateTime'
        versionId:
          type:
          - string
          - 'null'
        otherDetails:
          $ref: '#/components/schemas/ItemStructure'
    PartyProxy:
      type: 'null'
      properties:
        externalRef:
          $ref: '#/components/schemas/PartyRef'
    EhrStatus:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/DvText'
        archetypeNodeId:
          type: string
        uid:
          $ref: '#/components/schemas/UIDBasedId'
        archetypeDetails:
          $ref: '#/components/schemas/Archetyped'
        feederAudit:
          $ref: '#/components/schemas/FeederAudit'
        links:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Link'
        subject:
          $ref: '#/components/schemas/PartySelf'
        otherDetails:
          $ref: '#/components/schemas/ItemStructure'
        path:
          type: string
        is_modifiable:
          type: boolean
        is_queryable:
          type: boolean
    ReferenceRangeDvDateTime:
      type: object
      properties:
        range:
          $ref: '#/components/schemas/DvIntervalDvDateTime'
        meaning:
          $ref: '#/components/schemas/DvText'
    DvCodedText:
      type: 'null'
      properties:
        value:
          type: string
        hyperlink:
          $ref: '#/components/schemas/DvURI'
        formatting:
          type:
          - string
          - 'null'
        language:
          $ref: '#/components/schemas/CodePhrase'
        encoding:
          $ref: '#/components/schemas/CodePhrase'
        definingCode:
          $ref: '#/components/schemas/CodePhrase'
externalDocs:
  description: EHRbase Documentation
  url: https://docs.ehrbase.org/
